# Need these for a more recent environment on Linux
os:
  - linux
  - osx

language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-9 ;
      export CXX=g++-9 ;
    fi
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install pip ;
      sudo pip install gcovr ;
      cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE_TEST=1 -DCOVERAGE_USE_GCOVR=1 .. ;
    else
      cmake .. ;
    fi

script:
  - cmake --build .

after_script:
  - cmake --build . --target test
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake --build . --target cmdsuzdal_coverage ;
    fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      bash <(curl -s https://codecov.io/bash) ;
    fi

